# src/ui/screens/info_detail.py
# Pagini / continut pentru fiecare specializare (limba romana - fara diacritice)

PAGES = {
    "AIA": [
        "Automatica si Informatica Aplicata\n\nAutomatica si Informatica Aplicata este o specializare cu traditie de 30 de ani la Universitatea \"Dunarea de Jos\" din Galati. La finalul studiilor aveti cunostinte si competente profesionale: Utilizarea limbajelor si tehnologii informatice in scopul realizarii de aplicatii tehnice, de timp real sau de uz general: Dezvoltarea sistemelor de conducere automata si robotice si Dezvoltarea sistemelor bazate pe automate programabile, microcontrolere si sisteme embedded.",
        "Discipline:\n\n- Limbaje de programare                                       - Interfete utilizator si grafica\n- Automate programabile                                       - Sisteme de conducere a robotilor\n- Sisteme de timp real                                         - Inteligenta artificiala\n                                                                                             - Optimizari",
        "Urmand specializarea de Automatica si Informatica Aplicata ai acces:\n\n- Laboratoare moderne pentru toate disciplinele din domeniul automaticii si roboticii\n- Stagii de practica in companii si intreprinderi industriale locale si nationale\n- Oportunitati de angajare atat in domeniul automaticii, cat si al informaticii aplicate\n\nFinalizarea studiilor de licenta -> Masterat: Specializarea de Sisteme Informatice de Conducere Avansata\n                                                -> Doctorat in domeniul Ingineria Sistemelor",
        "De ce AIA?\n\nAIA combina informatica cu ingineria de control: inveti sa proiectezi sisteme care gandesc (algoritmi, AI) si actioneaza (senzori, actuatoare, control). Este pentru cei care vor sa construiasca roboti, sisteme embedded si aplicatii de control in timp real.\n\nCe inveti / ce faci diferit\n\n- Programare pentru sisteme in timp real, programare embedded (microcontrolere), automatizari industriale.\n- Concepte de control automat (PID, control adaptiv), electronica de baza si interfatare senzori/actuatori.\n- Integrarea inteligentei artificiale in sisteme fizice (viziune computerizata, procesare de semnal, planificare).\n- Project-based: construiesti prototipuri (roboti, drone, sisteme de achizitie), testezi in laborator.\n\nOportunitati / De ce sa alegi\n\n- Joburi in robotica, automatizari industriale, R&D in sisteme embedded, IoT, industria auto.\n- Proiecte hands-on reduc perioada pana la angajare; competentele sunt foarte cautate in fabrici inteligente si startup-uri hardware+software."

    ],
   "CTI": [
         "Calculatoare si Tehnologia Informatiei (CTI)\n\nVrei sa construiesti aplicatii care schimba lumea?\nLa UDJG, cu o traditie de peste 20 de ani, iti oferim formarea de inginer in informatica la standarde internationale. Aici inveti nu doar teorie, ci cum se fac aplicatii reale pe care le folosesc milioane de oameni.\n\nProgramul nostru urmeaza cele mai noi recomandari din industrie.",
         "Dupa absolvire, vei putea:\n\n- Proiecta si dezvolta aplicatii software complexe (aplicatii pentru telefon, web, desktop)\n- Construi sisteme distribuite si arhitecturi moderne\n- Administra si securiza retele de calculatoare\n- Gestiona proiecte IT in companii reale\n- Lucra cu multimedia, grafica si sisteme web-based avansat\n\nDe la idee la cod - tu controlezi!",         
         "Toolkit-ul unui inginer modern:\n\nLimbaje de programare: Java, C++, C#, Python, PHP\nBaze de date: Oracle, MySQL\nSisteme de operare & Retele: Linux, Windows, networking avansat\nDomenii noi: Web-based systems, Aplicatii mobile, Inteligenta artificiala, Robotica\n\nAceleasi tehnologii folosite de: Google, Microsoft, Amazon, startup-uri de succes.",
        "De ce CTI?\n\nCTI se concentreaza pe arhitecturi software si sisteme informatice: ideal pentru cei care vor sa dezvolte aplicatii, platforme web/mobile, sisteme distribuite si servicii cloud.\n\nCe inveti / ce faci diferit\n\n- Programare avansata (Java, C++, Python), structuri de date, algoritmi, baze de date, retele si securitate.\n- Proiectare de aplicatii (web, mobile), sisteme distribuite, DevOps, testare, optimizare performanta.\n- Dezvoltare software orientata pe echipe, folosind tool-uri profesionale (git, CI/CD, containere).\n\nOportunitati / De ce sa alegi\n\n- Joburi in dezvoltare software, backend/frontend, cloud engineering, securitate cibernetica, data engineering.\n- Tranzitie usoara catre startup-uri, companii IT mari sau roluri antreprenoriale; competente foarte portabile international."

    ],
   "IE": [
        "Inginerie Electrica (IE)\n\nElectricitatea alimenteaza lumea. Vrei sa fii cel care o controleaza?\nLa UDJG, alegi dintre 3 specializari care te pregatesc pentru viitorul energetic:\n\n- Inginerie Electrica si Calculatoare - combina traditia cu inovatia digitala\n- Electromecanica -> performanta si aplicatii practice\n- Electronica de Putere si Actionari Electrice -> universul fascinant al energiei electrice\n\nContinua cu Masterat si Doctorat în Inginerie Electrica!",   
        "Competente profesionale pe care le vei dobandi:\n\n- Proiecta instalatii electrice complexe pentru orase si industrii\n- Modela si simula actionarile electrice (motoare, convertoare, sisteme)\n- Asigura compatibilitatea electromagnetica si siguranta in orice mediu\n- Automatiza procese electromecanice cu tehnologie de varf\n- Lucra cu sisteme de achizitii de date si computere pentru control industrial\n\nDe la teorie la instalatii reale, tu faci diferenta!",
        "Conditii si oportunitati:\n\nLaboratoare moderne si echipamente profesionale pentru fiecare disciplina\nBurse de studiu nationale si internationale\nStagii practice in companii energetice si industrii\nProiecte care se folosesc in mediul real\n\nEnergie curata, cariere stralucitoare - viitorul energetic te asteapta!",
        "De ce IE?\n\nIE este axata pe generarea, transmiterea si utilizarea energiei electrice: potrivita pentru cei interesati de sisteme de putere, conversie energetica si infrastructura electrica.\n\nCe inveti / ce faci diferit\n\n- Proiectare instalatii electrice, conversie de putere, motoare si actionari, sisteme de distributie, protectii.\n- Analiza, simulare si modelare a sistemelor electrice; masuratori si instrumentatie.\n- Lucru cu echipamente mari (transformatoare, convertoare, centrale) si studii de compatibilitate electromagnetica.\n\nOportunitati / De ce sa alegi\n\n- Locuri de munca in companii energetice, firme de proiectare, industrie grea, furnizori de echipamente electrice, companii de energie regenerabila.\n- Roluri tehnice critice pentru tranzitia la surse de energie curate (eolian, fotovoltaic, retele inteligente)."

],
    "IETTI": [
            "Inginerie Electronica, Telecomunicatii si Tehnologii Informationale (IETTI)\n\nVrei sa construiesti tehnologia care face comunicarea si automatizarea posibila? La IETTI inveti bazele electronice si de telecomunicatii: componente si dispozitive, semnale si circuite, circuite integrate digitale si analogice, microprocesoare si microcontrolere. Vei putea intelege si proiecta sisteme reale folosite in industrie si medicina.",
            "Laboratoare si resurse moderne:\n\nPunem la dispozitie sali de curs si laboratoare dotate cu echipamente de ultima generatie, module electronice de dezvoltare pentru exercitii practice, retele de calculatoare si software specializat pentru studiu. Ai materiale tiparite si electronice, suport pentru proiecte si activitati extrascolare -> mediul perfect pentru invatare practica.",
            "Cariere si continuare academica:\n\nAbsolventii IETTI devin specialisti in proiectarea, implementarea si testarea echipamentelor electronice si a sistemelor de comunicatii folosite in procese industriale automatizate. Poti continua cu masteratul in Sisteme Electronice Avansate sau te poti alatura direct firmelor de profil (R&D, telecom, industria auto, IoT, medical). Studentii nostri sunt frecvent remarcati la competitii si recrutati de companii serioase.",
            "De ce IETTI?\n\nIETTI pregateste specialisti in electronica de semnal, comunicatii si sisteme embedded: pentru cei care vor sa proiecteze dispozitive electronice si solutii de comunicare.\n\nCe inveti / ce faci diferit\n\n- Electronica analogica si digitala, circuite integrate, RF, procesare de semnal, microcontrolere si sisteme de comunicatii.\n- Proiectare PCB, masuratori de laborator, dezvoltare module wireless si integrare hardware-software.\n- Aplicabilitate in telecomunicatii, IoT, sisteme medicale si industriale.\n\nOportunitati / De ce sa alegi\n\n- Joburi in design hardware, inginerie RF, testare echipamente, dezvoltare dispozitive IoT, R&D in telecom.\n- Posibilitate de colaborare stransa cu industria, proiecte practice si tranzitie rapida catre joburi ce implica prototipare hardware."
]
}

def get_page_text(spec_key, page_index):
    """
    Returneaza textul pentru `spec_key` (ex: 'CTI') si pagina `page_index` (0-based).
    Daca nu exista, returneaza un text fallback.
    """
    if not spec_key:
        return ""
    pages = PAGES.get(spec_key, [])
    if not pages:
        return f"{spec_key}\n\n(Detalii indisponibile)"
    idx = max(0, min(page_index, len(pages) - 1))
    return pages[idx]